### ISSUE TITLE
Integrate Phone Sign In

### ISSUE THREAD

**Issue by sbis04** [sbis04/flutterfire-samples#11]
Add Firebase Phone Sign-In as one of the authentication options and enable it in the dropdown of "Authentication".

**Comment by FaizFk** [comment]
Hi I would like this issue

**Comment by FaizFk** [comment]
Could you assign this issue to me

**Comment by sbis04** [comment]
This issue is currently not open to accept public contributions, so as you can see it's assigned to me. Actually, I'm doing some refactoring of this project structure. Once, it's done I will open a new set of issues having a "Hacktoberfest" label by this week.

**Comment by FaizFk** [comment]
Oh ok nevermind.
