### ISSUE TITLE
User presence tracking (Realtime database + Cloud functions)

### ISSUE THREAD

**Issue by sbis04** [sbis04/flutterfire-samples#19]
Showcase the user's presence tracking (online/offline) tracking, an example use case can be in any chat application. You can follow [this blog](https://blog.codemagic.io/user-presence-in-cloud-firestore-with-flutter) to implement it.

> **Please try to maintain similar theming across the pages, though there aren't any concrete theming guidelines for this contribution but keep this in mind for future-proofing this contribution.**

> Use the correct folder structure for adding the functionality, have a look at the readme and the project `lib` folder structure to understand the proper folder structure to follow. Each functionality is under its own category and consists mainly of `screens`, `utils`, and `widgets` folders.

> **NOTE:** You need to create your own Firebase project and configure it before starting to contribute, make sure you read the [CONTRIBUTING](https://github.com/sbis04/flutterfire-samples/blob/main/CONTRIBUTING.md) guidelines.

> Assume the Realtime Database & Cloud Firestore rules to be open to everyone (even without auth) for this demo.

More info: https://blog.codemagic.io/user-presence-in-cloud-firestore-with-flutter
Package to use: https://pub.dev/packages/firebase_database, https://pub.dev/packages/cloud_firestore

> **Hacktoberfest 2022 Note:** There's no assignment of issues (first come, first review basis), all eligible contributions will be given “hacktoberfest-accepted” label to make it count towards the Hacktoberfest contribution, even if it's not merged.

**Comment by rktejesh** [comment]
Hi @sbis04 
Can I work on this issue?

**Comment by sbis04** [comment]
Yes, you can start working on this @rktejesh. The structure of this project is not yet finalized, but you can add your code inside a new folder called `lib/backend_actions/user_presence`. Looking forward to your PR!
