### ISSUE TITLE
I can't see the users database

### ISSUE THREAD

**Issue by MuratovArthur** [sbis04/flutterfire-samples#3]
Your project is really great! 👍

I have cloned it and tested it on iOS to understand the concept of Firebase. All works fine and looks good, but I don't know how to access the list of registered users in the Firebase console. Can you help me with that? 

Thanks in advance!

**Comment by sbis04** [comment]
If I have understood your question correctly, you want access to the Firebase console dashboard, right? I think it would be quite difficult to give access of the Firebase console to so many users.
